### ISSUE TITLE
Breaks are not applied inside a table cell

### ISSUE THREAD

**Issue by efattal** [remarkjs/remark-breaks#6]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

lastest (3.0.2)

### Link to runnable example

https://stackblitz.com/edit/github-4rc9wa

### Steps to reproduce

- Add two spaces at the end of a text inside a table cell and type some text on the next line 
`|a|b|c|
|--|--|--|
|d|e|This paragraph  
should have a <br>|`

### Expected behavior

- The text should be rendered with a <br> inside the cell 

![image](https://user-images.githubusercontent.com/22234235/169842175-4c5f4f8b-4b6e-4942-b4cf-a98d58aee236.png)

### Actual behavior

The text of the 2nd line is considered as a new td in a new tr 
![image](https://user-images.githubusercontent.com/22234235/169841837-53721f73-54e4-4937-933c-b06c8bf62acf.png)

**Comment by wooorm** [comment]
That’s how GH works
