### ISSUE TITLE
How to prevent the break under definition lists

### ISSUE THREAD

**Issue by talatkuyuk** [remarkjs/remark-breaks#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

A definition list should provide lazy continuation in markdown. [example doc](https://michelf.ca/projects/php-markdown/extra/#def-list). 

For instance, the package `remark-definition-list` is a remark plugin for creating definition lists for markdown files supporting *lazy continuation* like below:
```markdown
Term 1

: Definition bla bla
with lazy continuation.
```
So, the definition above in `markdown` should not break.

### Possible Solution
If one of the parent/grand parents type is a `descriptiondetails` or `descriptionterm` or `descriptionlist`, the text node will be omitted without break.

You can have a look at the sample markdown AST for definition lists. [here](https://github.com/Symbitic/remark-plugins/tree/master/packages/remark-deflist#ast)

Maybe, the plugin can provide *an option* (optional) to provide the parent types in an array which is going to be omitted, like `{omit: ["descriptiondetails", "descriptionterm", "descriptionlist"]}` for giving flexibility to developers.

**Comment by wooorm** [comment]
> A definition list should provide lazy continuation in markdown. 

Okay, but why are you asking this here? I don‘t understand what you are asking.

**Comment by talatkuyuk** [comment]
The definition list plugin already provides lazy continuation, but the plugin `remark-breaks` prevents this and puts break even into definitions lists; and my request is how `remark-breaks` to omit/skip to put breaks into the text nodes related with definition lists.

**Comment by wooorm** [comment]
So, the definition list plugin adds support for definition lists. And this plugin adds support for breaks.

Why use this plugin if you don’t want breaks?

I also don’t understand why you are talking about lazy continuation? Whether the continuation is lazy or not shouldn’t matter?

Would you want normal lists, with (lazy or not) continuation to use breaks?

```markdown
- asd
qwe
```

^-- should there be a break or not?

If you only want breaks in certain cases, could you use escapes instead?

```markdown
asd\
qwe
```

^-- hard break! more info in the readme: https://github.com/remarkjs/remark-breaks#when-should-i-use-this

**Comment by talatkuyuk** [comment]
Got it, I am going to write a custom break plugin. Thank you for giving information.

**Comment by wooorm** [comment]
Ah okay. So you want to generally have breaks, except in certain nodes.
I recommend using [`mdast-util-find-and-replace`](https://github.com/syntax-tree/mdast-util-find-and-replace) then, it supports an `ignore` option!
