### ISSUE TITLE
Heading line breaks only render using alternative syntax

### ISSUE THREAD

**Issue by kara-todd** [remarkjs/remark-breaks#8]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.2

### Link to runnable example

https://codesandbox.io/s/remark-breaks-bug-example-by1dli

### Steps to reproduce

Code Snippet:
```JSX
import ReactMarkdown from "react-markdown";
import remarkBreaks from "remark-breaks";

const markdown = `
# Test h1 with
a linebreak

Test h1 with
a linebreak
===========

Test h2 with
a linebreak
-----------

## Test h2 with
a linebreak

Test paragraph with
a linebreak
`;

export default function App() {
  return (
    <div className="App">
      <ReactMarkdown remarkPlugins={[remarkBreaks]} children={markdown} />
    </div>
  );
}
```

### Expected behavior

Should render (whitespace added for readability)

```HTML
<h1>Test h1 with<br />a linebreak</h1>
<h1>Test h1 with<br />a linebreak</h1>

<h2>Test h2 with<br />a linebreak</h2>
<h2>Test h2 with<br />a linebreak</h2>

<p>Test pagaraph with<br />a linebreak</p>
```

### Actual behavior

It instead renders (whitespace added for readability)

```HTML
<h1>Test h1 with</h1>
<p>a linebreak</p>
<h1>Test h1 with<br />a linebreak</h1>

<h2>Test h2 with<br />a linebreak</h2>
<h2>Test h2 with</h2>
<p>a linebreak</p>

<p>Test pagaraph with<br />a linebreak</p>
```

**Comment by kara-todd** [comment]
I'm not sure if this should be a bug for this plugin or for `react-markdown`. It seems like the standard heading syntax is getting parsed separately into `h1` and `p` elements... but I'm not sure what step in the process it is occurring on...  The alternative syntax allows a workaround for header levels 1 and 2, but it doesn't seem like line breaks can be added for levels 3-6...

**Comment by wooorm** [comment]
Hi Kara. What you describe as a problem is how (ATX) headings work. Read about it in [the spec](https://spec.commonmark.org/0.30/#atx-headings) or try it out here on GitHub.
What you describe as the behavior you want does not align with the spec, so that isn’t going to happen.
