### ISSUE TITLE
Move transformer into `mdast-util-breaks`

### ISSUE THREAD

**Issue by remcohaszing** [remarkjs/remark-breaks#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The transformer can work on the AST without unified. It may be useful to use this as a plain function.

### Solution

Move the transformer into a new package `mdast-util-breaks`. This package would be part of [syntax-tree](https://github.com/syntax-tree).

### Alternatives

I chose the name to match the name `remark-breaks`, but it may make sense to use something more verbose, e.g.: `mdast-util-break-newlines`.

**Comment by ChristianMurphy** [comment]
Sounds good to me, thanks @remcohaszing!
the more verbose name `mdast-util-break-newlines` sounds better to me, but interested to hear others thoughts.

**Comment by wooorm** [comment]
Yeah, sure.

Why not `mdast-util-hard-break`? `mdast-util-automatic-break`? `mdast-util-auto-hard-break`?  `mdast-util-newline-to-break`? (optionally with `s` suffix)

I’m not sure what `break-newlines` means, it feels “inverted”.

I think `mdast-util-newline-to-break` is my preference.

**Comment by remcohaszing** [comment]
> I’m not sure what `break-newlines` means, it feels “inverted”.

It works if you read _“break”_ as a verb.

Anyway, I like `mdast-util-newline-to-break` too. I’ll go with that. I’ll get to it later this week.

What license should I use? Since it’s going to be mostly based on this repo, copy the license as-is?

**Comment by wooorm** [comment]
That could be an explanation, but then I think that’s a bit weird, wouldn’t you break the lines instead? `break-lines`?

> What license should I use?

Yep, reuse the one seems fine.

---

I think you could also go with:

```
/**
 * @typedef {import('mdast').Root} Root
 * @typedef {import('mdast').Content} Content
 * @typedef {import('mdast-util-find-and-replace').ReplaceFunction} ReplaceFunction
 */

/**
 * @typedef {Content | Root} Node
 */

import {findAndReplace} from 'mdast-util-find-and-replace'

/**
 * Turn normal line endings into hard breaks.
 *
 * @param {Node} tree
 *   Tree to change.
 * @returns {void}
 *   Nothing.
 */
export function newlineToBreak(tree) {
  findAndReplace(tree, /\r?\n|\r/g, replace)
}

/**
 * Replace line endings.
 *
 * @type {ReplaceFunction}
 * @param {string} value
 */
function replace(value) {
  return [{type: 'break'}, {type: 'text', value}]
}
```

This is what I have locally now in `rehype-github-*`

AFAIK it is mostly equivalent: because line endings can never occur at the start or end of a paragraph, or next to each other (blank lines).

Though this `findAndReplace` method would split the line endings from the next text? Maybe `findAndReplace` should be updates to merge initial/final text node results?

Looking at the current algo, it actually drops all positional info on text nodes? 🤔
